name: Push Container to Server

on:
  push:
    branches:
      - location

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Container
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: yuhao10/actiontest:latest

    - name: SSH into Server
      uses: appleboy/ssh-action@master
      with:
        host: "62.72.36.174"
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}

    - name: Deploy Container
      run: |
        cd /home
        mdkir actiontest
         

    
